name: M8web

# Controls when workflow will run
on:
  # Trigger the workflow on push or pull request events but only for the specified paths
  push:
    paths:
      - 'git-terraform/M8/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      action_type:
        description: 'What action should be performed? (apply or destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - 'apply'
          - 'destroy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "resourcegroups"
  resourcegroups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: 'M8web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: 'git-terraform/M8'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runner's shell
      - name: 'Terraform init'
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform plan'
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform apply'
        if: github.event.inputs.action_type == 'apply'
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform destroy'
        if: github.event.inputs.action_type == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
      


